### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Igor-Adlab** [cdmbase/graphql-rabbitmq-subscriptions#1]
Can not connect to CloudAMQP instance using their connection string: amqp://iypbjclh:VB1-3JxyCOuZDoFiU1C7Wr5ofxpJ0co7@cat.rmq.cloudamqp.com/iypbjclh.

Subscription failing

**Comment by vedebel** [comment]
Try to add / to the path. 
It will look like amqp://iypbjclh:VB1-3JxyCOuZDoFiU1C7Wr5ofxpJ0co7@cat.rmq.cloudamqp.com//iypbjclh.

**Comment by veeramarni** [comment]
@igor-adlab does that fix your issue?
