### ISSUE TITLE
Unable to pass the socket options to rabbitmq connections

### ISSUE THREAD

**Issue by ganeshpms** [cdmbase/graphql-rabbitmq-subscriptions#13]
The pubsub works fine with simple URL host, port or connection string. I want to connect to the rabbitmq using amqps, for that, I need to pass the 'socket options' which will be used by amqb lib connect method. I couldn't find the way in the current implementation. Could you please help on that?

**Comment by the-noob** [comment]
If your config has `host` and `port` it will be treated as a config string.
If you pass `hostname` instead of `host` in config it should work.
