### ISSUE TITLE
Every publish event creates a brand new channel

### ISSUE THREAD

**Issue by zestsystem** [cdmbase/graphql-rabbitmq-subscriptions#20]
Subscribers respond to the events being fired but the problem is that it creates a new channel per event and only two channels process these events anyway and rest remain idle (demonstrated by the pic below).  After a while, the rabbitmq hits "No channels left to allocate error".

Why are we creating a new channel per event? Why can't it use one channel to process all notification events? Let me know if there is something I'm doing wrong with implementation...  

Thank you for your time and help

<img width="1920" alt="Screen Shot 2022-05-15 at 8 25 14 PM (2)" src="https://user-images.githubusercontent.com/39456023/168514809-aff9b481-2a67-47b6-b5e6-2f336d980216.png">

pubsub instantiation

```typescript

export const pubsub = new AmqpPubSub({ logger });

//new follow event happens every second
setInterval(function () {
  pubsub.publish('new_follow', { id: 'hello' , username: 'help'});
}, 1000);

```

And implementation of subscriber (I use graphql nexus) 

```typescript
import { pubsub } from './../infra/rabbitmq/rabbitmq';
import { subscriptionField, objectType, extendType } from 'nexus';

export const NewFollowSubscription = subscriptionField('newFollow', {
  type: 'NewFollowSubscriptionPayload',

  subscribe: (_, args, ctx) => {
    return pubsub.asyncIterator('new_follow');
  },
  resolve(payload) {
    console.log('payload: ', payload);
    return {
      follower: {
        id: payload.id,
        username: payload.username,
      },
    };
  },
});

export const NewFollowSubscriptionPayload = objectType({
  name: 'NewFollowSubscriptionPayload',
  definition(t) {
    t.nonNull.field('follower', { type: 'User' });
  },
});



```

**Comment by MallamTY** [comment]
Hello,

Have you been able to resolve this or find an alternative to it?
I am working on a project currently and I have implemented this before notificing the issue

**Comment by zestsystem** [comment]
@MallamTY  I found an alternative. I think it would help to post an answer here if you would like to provide one :) I will close this issue after.

**Comment by MallamTY** [comment]
I haven't been unable to get a solution either @zestsystem.

**Comment by MallamTY** [comment]
Is there a way we can connect outside this conversation?

I will be glad if you can help with the alternative
