### ISSUE TITLE
What's `logger`?

### ISSUE THREAD

**Issue by giautm** [cdmbase/graphql-rabbitmq-subscriptions#4]
I read example and still dont understand what's `logger`. How i make it work?
```
import { AmqpPubSub } from 'graphql-rabbitmq-subscriptions';
const logger = <log function>;
const pubsub = new AmqpPubSub({logger});
const subscriptionManager = new SubscriptionManager({
  schema,
  pubsub,
  setupFunctions: {},
});
```

**Comment by giautm** [comment]
And how i can removed `logger` if don't need?

**Comment by veeramarni** [comment]
Its Bunyan logger implementation. I will make it optional. See @cdm-logger/server, to implement logging.

**Comment by giautm** [comment]
Tks for the answer, so i close this issues. 😄
