### ISSUE TITLE
asyncIterator support

### ISSUE THREAD

**Issue by groundmuffin** [cdmbase/graphql-rabbitmq-subscriptions#5]
Hi,
the new version of graphql-sibscription lib uses the special object with subscribe property, that returns asyncIterator object. Subscription Manager is deprecated. Do you have plans to add asyncIterator support?

**Comment by developerworks** [comment]
![graphql-rabbitmq-subscription](https://user-images.githubusercontent.com/725190/29250889-3eca9174-807d-11e7-98fb-f3aba6135f96.gif)

Just a workable fork. you can `yarn add https://github.com/developerworks/graphql-rabbitmq-subscriptions.git`.

There is a [demo](https://github.com/developerworks/graphql-rabbitmq-subscriptions-demo)

**Comment by veeramarni** [comment]
@developerworks  would you mind creating a PR?

**Comment by developerworks** [comment]
The fork repo have `dist` folder, i think it's not suitable for PR. i will make a new repo for PR in later.

**Comment by developerworks** [comment]
`Add AsyncIterator Support` PR
@veeramarni 
https://github.com/cdmbase/graphql-rabbitmq-subscriptions/pull/8

**Comment by developerworks** [comment]
logger issue:

TypeError: logger.child is not a function
1|gm-agent |     at Object.createChildLogger (/home/www/servers/gm-agent-server/node_modules/graphql-rabbitmq-subscriptions/src/child-logger.ts:4:17)

```js
var server = require("@cdm-logger/server");
var settings = {
  level: "info",
  mode: "short" // Optional: default 'short' ('short'|'long'|'dev'|'raw')
};
var cdmlogger = server.ConsoleLogger.create("pubsub", settings);
cdmlogger.level('trace')


export const pubsub = new AmqpPubSub({
  config: {
    host: config.RABBITMQ_HOST,
    port: config.RABBITMQ_PORT,
  },
  connectionListener: (err) => {
    if (err) {
      logger.error('connect to rabbitmq error ', err)
    } else {
      logger.info('connected to rabbitmq')
    }
  },
  logger: cdmlogger
})

```

**Comment by veeramarni** [comment]
`version 1.1.0` now supports `asyniterator`
